name: trivia_cli
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: '^3.8.1'

dependencies:
  http: ^1.2.0
  logging: ^1.2.0
  terminal_colors:
    path: ../terminal_colors
  trivia_api:
    path: ../trivia_api

dev_dependencies:
  test: ^1.24.0